orienteering.pk.HaversineDistance Class Reference
Implementation Haversine Distance Algorithm between two points.
Static Public Member Functions
static double dist (double lat1, double lon1, double lat2, double lon2)
Static Private Member Functions
static Double toRad (Double value)
Detailed Description
Implementation Haversine Distance Algorithm between two points.
See also
See source here.
R = earth’s radius (mean radius = 6,371km)
Δlat = lat2− lat1
Δlong = long2− long1
a = sin²(Δlat/2) + cos(lat1).cos(lat2).sin²(Δlong/2)
c = 2.atan2(√a, √(1−a))
d = R.c
Parameters
lat1 : latitude point 1
lon1 : longitude point 1
lat2 : latitude point 2
lon2 : latitude point 2
Returns
distance: distance in km between the two points
Member Function Documentation
dist()
static double orienteering.pk.HaversineDistance.dist (double lat1, double lon1, double lat2, double lon2) [inline], [static]
References orienteering.pk.HaversineDistance.toRad().
Referenced by orienteering.pk.Orienteering.computeDistances().
toRad()
static Double orienteering.pk.HaversineDistance.toRad (Double value) [inline], [static], [private]
Referenced by orienteering.pk.HaversineDistance.dist().
The documentation for this class was generated from the following file:
src/ HaversineDistance.java