Orienteering Class Reference
Project Main Class.
Static Public Member Functions
static void main (String[] args)
Main Algorithm.
static void computeDistances (double[][] timeMatrix)
Compute distance matrix using haversine function.
static void insertionHeuristic (Solution route)
Greedy construction of a solution via insertion.
static boolean twoOptHeuristic (Solution route)
2-Opt move: One site from outSet moves in and one site from inSet is out.
static boolean repairHeuristic (Solution route)
Repair current solution to balance number of C and N.
Static Public Attributes
static Random random
random number generator
static double latitude = 51.533241
Latitude Home point.
static double longitude = -0.104839
static int stochastic = 0
Longitude Home point.
static int home = 0
default id of HOME node
static int nSites = 0
static ArrayList< Record > DataFrame = new ArrayList<Record>()
static double [] lat
latitude of each site
static double [] lon
longitude of each site
static int [] danger
whether a site is endangered (1) or not (0)
static String [] country
country iso code of each site
static String [] category
category (C, N, or C/N) of each site
static double [][] timeMatrix
nSites x nSites travel time matrix
static Solution bestRoute = new Solution(home, nSites)
Detailed Description
Project Main Class.
This code solves a variant of the Orienteering problem. A thorough presentation of the model is found in the document summary.pdf under the folder docs/summary. please, have a look at that document to find a description of the algorithm.
This class implements the four heuristics of the Iterative Local Search algorithm, namely:
the insertionHeuristic()
the twoOptHeuristic()
the repairHeuristic()
the randomRemoveOne()
Member Function Documentation
computeDistances()
static void Orienteering.computeDistances (double timeMatrix[][]) [inline], [static]
Compute distance matrix using haversine function.
This function return the timeMatrix matrix. The matrix is triangular. However, we keep here the full matrix, for ease of access.
NOTE: This is not a distance matrix. The values are travel times across points, since the distance in km is divided by the travel speed (in km/minute).
Currently, we have that the travel speed is 80km/h, i.e., 80/60 km/min.
See also
HaversineDistance()
References HaversineDistance.dist(), and nSites.
Referenced by main().
insertionHeuristic()
static void Orienteering.insertionHeuristic (Solution route) [inline], [static]
Greedy construction of a solution via insertion.
Starting from a solution of type $\textbf{x} = ( 0, 0) $, where $\textbf{x}$ indicates the home (starting and ending point), we progressively add, in a greedy fashion, the most promising site. The attractiveness of a site is measured using the followinwing score:
\sigma_{ij} = \frac{\Delta z_i}{\Delta t_{ij}} 
 where $\Delta z_i$ is the increase in the objective function value associated to the inclusion of the $i^{th}$ site, and $\Delta t_{ij}$ is the increase in time due to the introduction of site $i$ after site $j$ (which is obviously in the current solution.)
Therefore, for each cycle of the greedy heuristic, we determine (i) which candidate should be added to the current solution (if any) and (ii) in which position w.r.t. the sites in the current solution.
The insertion mechanism is repeated as long as the budget constraint is not violated. The greedy mechanism stops when either no item currently not in the solution fits within the budget limits, or no items are left in the outSet.
Referenced by main().
main()
static void Orienteering.main (String [] args) [inline], [static]
Main Algorithm.
This algorithm implements an Iterative Local Search (ILS) heuristic scheme for a variant of the Orienteering problem. < count nr iterations without improvements
< iteration counter
References category, computeDistances(), country, insertionHeuristic(), latitude, longitude, nSites, ReadCSV.readData(), repairHeuristic(), and twoOptHeuristic().
repairHeuristic()
static boolean Orienteering.repairHeuristic (Solution route) [inline], [static]
Repair current solution to balance number of C and N.
The balance constraint is addressed here. The 2-Opt and the construction heuristic work on a 'relaxed' version of the original problem. The constraint that states that an equal number of sites of type C and N should be visited (where sites of type C/N can be accounted for both ways) has not been considered. Therefore, after any of the two heuristic mechanisms, it is quite possible that the solution is not feasible with respect to the balance constraint.
A repair heuristic is implemented here in two steps: We first identify the imbalance. For example, as in the case of the unesco dataset, assume that we have more C than N. We need a repair mechanism when:
 |n_C - n_N | > n_{MIX} + 1 
 In other words, we allow for a maximal discrepancy of 1 site, as opposed to imposing that exactly the same number of sites of the two types are visited. This latter interpretation of the requirement would force the solution to contain an even number of sites (which seems to be too restrictive.) Here, instead, we admit a maximum difference of one site for one of the two categiries. If this interpretation is not acceptable, it suffices to remove one extra site from the solution produced by this function.
Attempt to swap one element from cateogry C currently in inSet with one element of category N from outSet. We select the one with the best effect on the objective function value (even if negative).
If the repair mechanism fails, randomly remove one element from inSet among those sites with Category C.
References category, country, danger, home, latitude, longitude, nSites, random, and timeMatrix.
Referenced by main().
twoOptHeuristic()
static boolean Orienteering.twoOptHeuristic (Solution route) [inline], [static]
2-Opt move: One site from outSet moves in and one site from inSet is out.
An Iterative Local Search (ILS) approach is used here. We start from an initial solution, typically built via insertionHeuristic(). Next, we define a neighborhood as the set of solutions that can be reached from the incumbent swapping one site in inSet with one site from outSet. In this Neighborhood, we select the solution, among the feasible ones, that leads to the maximum increase in the objective function value.
At each step of the ILS, two cases can arise:
An improving solution has been found: In this case, we set this solution as incumbent and we draw a neighborhood around the new incumbent. The local search restarts for a new iteration.
An improving solution has not been found in the current Neighborhood. We could apply a, e.g., Variable Neighborhood Search, to increase the neighborhood size around the incumbent and restart with the ILS. We did not implement such as scheme. In this version of the code, when an improving solution has not been found, we stop and terminate the 2-Opt heuristic.
A classical 2-Opt move is implemented as follows. Assume a solution of the following type is given:
 \textbf{x} = (\ldots, p_j, j, n_j, \ldots) 
 where $j$ has been chosen for exclusion from $\textbf{x}$, and $p_j$ and $n_j$ are the elements preceding and followining $j$, respectively. In addition, assume that element $k$ is selected for insertion.
A move that swaps $j$ with $k$ has the following $\Delta_{kj}$ and the following $\Delta t_{kj}$:
Referenced by main().
Member Data Documentation
bestRoute
Solution Orienteering.bestRoute = new Solution(home, nSites) [static]
category
String [] Orienteering.category [static]
category (C, N, or C/N) of each site
Referenced by main(), and repairHeuristic().
country
String [] Orienteering.country [static]
country iso code of each site
Referenced by main(), and repairHeuristic().
danger
int [] Orienteering.danger [static]
whether a site is endangered (1) or not (0)
Referenced by repairHeuristic().
DataFrame
ArrayList<Record> Orienteering.DataFrame = new ArrayList<Record>() [static]
Referenced by ReadCSV.readData().
home
int Orienteering.home = 0 [static]
default id of HOME node
Referenced by repairHeuristic().
lat
double [] Orienteering.lat [static]
latitude of each site
latitude
double Orienteering.latitude = 51.533241 [static]
Latitude Home point.
Referenced by main(), and repairHeuristic().
lon
double [] Orienteering.lon [static]
longitude of each site
longitude
double Orienteering.longitude = -0.104839 [static]
Referenced by main(), and repairHeuristic().
nSites
int Orienteering.nSites = 0 [static]
Referenced by computeDistances(), main(), and repairHeuristic().
random
Random Orienteering.random [static]
random number generator
Referenced by repairHeuristic().
stochastic
int Orienteering.stochastic = 0 [static]
Longitude Home point.
set to 1 if stochastic, 0 if determ
timeMatrix
double [][] Orienteering.timeMatrix [static]
nSites x nSites travel time matrix
Referenced by repairHeuristic().
The documentation for this class was generated from the following file:
src/ Orienteering.java